version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.develop
    tty: true
    # Go アプリではなく、ここではホットリローダー air を起動しておく
    command: air -c .air.toml
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: .
        target: /go/src/app
      - type: volume
        source: go-modules
        target: /go/pkg/mod
volumes:
  go-modules:
